language: cpp

compiler:
  - gcc

before_install:
  # g++4.9.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  - sudo apt-get update -qq

  # libraries install
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
  - sudo apt-get install cmake libboost-all-dev libeigen3-dev libopencv-dev libcv-dev

  # sfml install
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2 --no-check-certificate
  - tar -xjvf /tmp/sfml.tar.bz2
  - export SFML_ROOT=SFML-2.1/
  
  # nlopt install
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O /tmp/nlopt.tar.gz --no-check-certificate
  - tar -xvf /tmp/nlopt.tar.gz
  - cd nlopt-2.4.2
  - sh autogen.sh
  - make
  - make install
  - cd ..
  
install:
  # g++4.9.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  - mkdir build && cd build && cmake .. && make
  - cd ../bin && ok=true; for i in `echo test*`; do "./"$i; if [ $? -ne 0 ]; then ok=false; fi; done; $ok;
