language: cpp

compiler:
  - gcc

before_install:
  # g++4.9.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  - sudo apt-get update -qq

  # libraries install
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 
  - sudo apt-get install cmake libboost-all-dev libeigen3-dev libopencv-dev libcv-dev

  # sfml install
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2 --no-check-certificate
  - tar -xjvf /tmp/sfml.tar.bz2
  - export SFML_ROOT=SFML-2.1/
  
  # nlopt install
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz -O /tmp/nlopt.tar.gz --no-check-certificate
  - tar -xvf /tmp/nlopt.tar.gz
  - cd nlopt-2.4.2
  - ./configure && make && sudo make install
  - cd ..

  # artoolkit install
  - wget http://www.artoolkit.org/dist/artoolkit5/5.3/ARToolKit5-bin-5.3.2r1-Linux-x86_64.tar.gz -O /tmp/artoolkit.tar.gz --no-check-certificate
  - mkdir artoolkit5
  - cd artoolkit5
  - tar -xvf /tmp/artoolkit.tar.gz
  - echo -e 'n\ny\ny\nn\nn\nn\nn\nn\n' | ./Configure
  - ./share/artoolkit5-setenv
  - cd ..
  
install:
  # g++4.9.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  - cd artoolkit5
  - cd lib/SRC
  - make 
  - cd ../../..
  - mkdir build && cd build && cmake .. && make
  - cd ../bin && ok=true; for i in `echo test*`; do "./"$i; if [ $? -ne 0 ]; then ok=false; fi; done; $ok;
