# - Try to find the artoolkit5 library
# Once done this will define
#
#  ARTOOLKIT5_FOUND - system has ARTOOLKIT5
#  ARTOOLKIT5_INCLUDE_DIR - the ARTOOLKIT5 include directory
#  ARTOOLKIT5_LIBRARIES - Link these to use ARTOOLKIT5
#  ARTOOLKIT5_LINK_DIRECTORIES - link directories, useful for rpath
#

if (ARTOOLKIT5_INCLUDE_DIR AND ARTOOLKIT5_LIBRARIES)

	# in cache already
	SET(ARTOOLKIT5_FOUND TRUE)

else (ARTOOLKIT5_INCLUDE_DIR AND ARTOOLKIT5_LIBRARIES)

	if (WIN32)

		# check whether the ARTOOLKIT5DIR environment variable is set and points to a 
		# valid windows ARTOOLKIT5 installation
		FIND_PATH(
			ARTOOLKIT5_DIR include/AR/ar.h
			PATHS $ENV{ARTOOLKIT5_ROOT}/
			DOC "The main directory of the ARTOOLKIT5 library, containing the subfolders include and lib" )

		if (ARTOOLKIT5_DIR)
			SET(ARTOOLKIT5_INCLUDE_DIR ${ARTOOLKIT5_DIR}/include CACHE PATH "ARTOOLKIT5 include directory")
			SET(ARTOOLKIT5_LINK_DIRECTORIES ${ARTOOLKIT5_DIR}/lib CACHE PATH "ARTOOLKIT5 link directory")
			FIND_LIBRARY(ARTOOLKIT5_LIBRARIES
				NAME
				libARgsub_lite.a libARvideo.a libAR.a libARICP.a
				HINTS
				${ARTOOLKIT5_DIR}/lib/libARgsub_lite.a
				${ARTOOLKIT5_DIR}/lib/libARvideo.a
				${ARTOOLKIT5_DIR}/lib/libARICP.a
				${ARTOOLKIT5_DIR}/lib/libAR.a
				PATHS
				${ARTOOLKIT5_DIR}/lib)
			SET(ARTOOLKIT5_FOUND TRUE)
		else (ARTOOLKIT5_DIR)
			SET (ARTOOLKIT5_FOUND FALSE)
		endif (ARTOOLKIT5_DIR)

	else (WIN32)

		FIND_PATH(ARTOOLKIT5_INCLUDE_DIR
			AR/ar.h
			PATHS $ENV{ARTOOLKIT5_ROOT}/include
			/usr/include)
		# message(STATUS "Found ARTOOLKIT5: ${ARTOOLKIT5_INCLUDE_DIR}")     
		FIND_LIBRARY(ARTOOLKIT5_gsub_lite_LIBRARY NAMES ARgsub_lite
			PATHS
			$ENV{ARTOOLKIT5_ROOT}/lib
			/usr/lib
			/usr/lib64)
		FIND_LIBRARY(ARTOOLKIT5_video_LIBRARY NAMES ARvideo
			PATHS
			$ENV{ARTOOLKIT5_ROOT}/lib
			/usr/lib
			/usr/lib64)
		FIND_LIBRARY(ARTOOLKIT5_ICP_LIBRARY NAMES ARICP
			PATHS
			$ENV{ARTOOLKIT5_ROOT}/lib
			/usr/lib
			/usr/lib64)
		FIND_LIBRARY(ARTOOLKIT5_AR_LIBRARY NAMES AR
			PATHS
			$ENV{ARTOOLKIT5_ROOT}/lib
			/usr/lib
			/usr/lib64)
		set(ARTOOLKIT5_LIBRARIES ${ARTOOLKIT5_gsub_lite_LIBRARY};${ARTOOLKIT5_video_LIBRARY};${ARTOOLKIT5_ICP_LIBRARY};${ARTOOLKIT5_AR_LIBRARY})
		if(ARTOOLKIT5_INCLUDE_DIR AND ARTOOLKIT5_gsub_lite_LIBRARY AND ARTOOLKIT5_video_LIBRARY AND ARTOOLKIT5_ICP_LIBRARY AND ARTOOLKIT5_AR_LIBRARY)
			set(ARTOOLKIT5_FOUND TRUE)
		endif(ARTOOLKIT5_INCLUDE_DIR AND ARTOOLKIT5_gsub_lite_LIBRARY AND ARTOOLKIT5_video_LIBRARY AND ARTOOLKIT5_ICP_LIBRARY AND ARTOOLKIT5_AR_LIBRARY)
		
	endif (WIN32)

	if (ARTOOLKIT5_FOUND)
		message(STATUS "Found ARTOOLKIT5: ${ARTOOLKIT5_LIBRARIES}")
	else (ARTOOLKIT5_FOUND)
		if (ARToolKit5_FIND_REQUIRED)
			message(FATAL_ERROR "Could NOT find ARTOOLKIT5")
		else (ARToolKit5_FIND_REQUIRED)
			message(STATUS "Could NOT find ARTOOLKIT5")
		endif (ARToolKit5_FIND_REQUIRED)
	endif (ARTOOLKIT5_FOUND)


endif (ARTOOLKIT5_INCLUDE_DIR AND ARTOOLKIT5_LIBRARIES)
